import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import { CookiesProvider } from "next-client-cookies/server";
import { DarkModeContextProvider } from "@/contexts/DarkModeContext";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { UserContextProvider } from "@/contexts/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Gelianthus' Field",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className="scroll-pt-20 sm:scroll-pt-28"
		>
			<head>
				<link
					rel="icon"
					href="/images/logo.webp"
					sizes="any"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
					rel="stylesheet"
				/>
			</head>
			<body className={inter.className}>
				<Provider>
					<CookiesProvider>
						<DarkModeContextProvider>
							<UserContextProvider>
								<div className="flex flex-col min-h-screen">
									<Header />
									{children}
									<Footer />
								</div>
							</UserContextProvider>
						</DarkModeContextProvider>
					</CookiesProvider>
				</Provider>
			</body>
		</html>
	);
}
