import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import { CookiesProvider } from "next-client-cookies/server";
import { DarkModeContextProvider } from "@/contexts/DarkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Gelianthus' Blogsite",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
					rel="stylesheet"
				/>
			</head>
			<body className={inter.className}>
				<Provider>
					<DarkModeContextProvider>
						<CookiesProvider>{children}</CookiesProvider>
					</DarkModeContextProvider>
				</Provider>
			</body>
		</html>
	);
}
